export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const ORDER_MINE_LIST_REQUEST = 'ORDER_MINE_LIST_REQUEST'
export const ORDER_MINE_LIST_SUCCESS = 'ORDER_MINE_LIST_SUCCESS'
export const ORDER_MINE_LIST_FAIL = 'ORDER_MINE_LIST_FAIL'

// Admin Constant
export const ORDER_ALL_LIST_REQUEST = 'ORDER_ALL_LIST_REQUEST'
export const ORDER_ALL_LIST_SUCCESS = 'ORDER_ALL_LIST_SUCCESS'
export const ORDER_ALL_LIST_FAIL = 'ORDER_ALL_LIST_FAIL'

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'

export const ORDER_SORT_LIST_SORTING = 'ORDER_SORT_LIST_SORTING'
export const ORDER_SORT_LIST_DEFAULT = 'ORDER_SORT_LIST_DEFAULT'
export const ORDER_SORT_LIST_ISPAID = 'ORDER_SORT_LIST_ISPAID'
export const ORDER_SORT_LIST_ISNOTPAID = 'ORDER_SORT_LIST_ISNOTPAID'
export const ORDER_SORT_LIST_ISDELIVERED = 'ORDER_SORT_LIST_ISDELIVERED'
export const ORDER_SORT_LIST_ISNOTDELIVERED = 'ORDER_SORT_LIST_ISNOTDELIVERED'
export const ORDER_SORT_LIST_ERROR = 'ORDER_SORT_LIST_ERROR'
